import { StyleSheet } from 'react-native';
import { colors } from '@/constants/theme';
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background },
  scroll: { flexGrow: 1, paddingBottom: 95 },
  back: { marginLeft: 16, width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  content: { width: '100%', maxWidth: 440, paddingHorizontal: 28, alignSelf: 'center' },
  brand: { alignItems: 'center', marginTop: 0, marginBottom: 34 },
  title: { fontSize: 27, fontWeight: '700', color: colors.ink, letterSpacing: -0.8 },
  subtitle: { fontSize: 14, lineHeight: 21, color: colors.muted, marginTop: 7, marginBottom: 22 },
  fields: { gap: 12 }, options: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', marginVertical: 13 },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', minHeight: 44, gap: 8 },
  checkbox: { width: 15, height: 15, borderRadius: 3, borderWidth: 1, borderColor: '#91A397', justifyContent: 'center', alignItems: 'center' },
  optionText: { fontSize: 11, color: colors.muted }, legalLinks: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 5 },
  inlineLink: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 2 }, linkSmall: { fontSize: 11, color: colors.leaf, fontWeight: '500' },
  error: { color: colors.error, fontSize: 12, marginBottom: 12 },
  notice: { backgroundColor: colors.mint, padding: 14, borderRadius: 12, marginTop: 15 },
  noticeText: { fontSize: 13, color: colors.green, lineHeight: 20 },
  divider: { flexDirection: 'row', alignItems: 'center', gap: 13, marginVertical: 24 },
  line: { height: 1, flex: 1, backgroundColor: colors.line },
  dividerText: { fontSize: 11, color: colors.muted },
  socials: { flexDirection: 'row', gap: 12 },
  social: { flex: 1, height: 52, borderRadius: 16, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF55' },
  switchRow: { marginTop: 18, flexDirection: 'row', gap: 7, justifyContent: 'center', alignItems: 'center' },
  switchText: { fontSize: 12, color: colors.muted }, link: { fontSize: 12, color: colors.green, fontWeight: '700' },
  preview: { minHeight: 44, justifyContent: 'center', alignItems: 'center' }, previewText: { fontSize: 12, color: colors.muted },
  scrim: { flex: 1, backgroundColor: '#122B2580', justifyContent: 'center', padding: 24 },
  modal: { backgroundColor: colors.background, borderRadius: 24, padding: 24, gap: 14, width: '100%', maxWidth: 440, alignSelf: 'center' },
  close: { position: 'absolute', right: 12, top: 10, width: 44, height: 44, alignItems: 'center', justifyContent: 'center', zIndex: 1 },
});
